### PR TITLE
Python3 update for Histogram Drawing

### PR DESCRIPTION
**Pull request by janthamade**

### CODE REVIEW

**Comment by miranov25** [comment]
Hello Alperen.
I prefer to push only notebooks without data. Othrwise the git size will explode.
Could you clean notebook and redo the request?

**Comment by janthamade** [comment]
-PWGPP-527 Histogram visualization is added
-drawhisto.py is updated for python3

**Comment by miranov25** [comment]
@janthamade 
Thank you for commit.  In order to keep the git repository small (no binary information) I suggest to squash information.
The easiest way will be to backup you changes (make branch), and apply your modification on top of my current master  as a one commit.  This you can make as a one commit.  I'm not sure when I will come today (mounting furniture with external firma). In case we can meet on Vidyo
for the moment I suggest to close this pull request and open new one with one commit modification

**Comment by miranov25** [comment]
### For the drawHisto.py I suggest to do following:
* rename to bokehDrawHistoTHn
* **mv file to the RootInteractive - so it can be used by all root users**
* use options in similar way as I started to use them
  * see e.g.  (line>124)
https://github.com/miranov25/RootInteractive/blob/0a0e313bac56722948e066953e5ee3c94fdebe18/RootInteractive/InteractiveDrawing/bokeh/bokehTools.py

**I would like to have this change in new Release. So it should be comitted today**

**Pull request closed without merging**
