### PR TITLE
PWGPP-576 adding minuit fitter

### PR DESCRIPTION
**Pull request by pl0xz0rz**
This PR:
-Fixes a bug which creates the wrong number of initial parameters when the number of fits differs from the number of bootstrap samples
-Adds a Minuit-based fitter to the benchmark

### CODE REVIEW

**Comment by miranov25** [comment]
Could you put there results of test to the github?

**Comment by pl0xz0rz** [comment]
30 fits with 30 bootstrap samples each, 1000 to 100000 points
### Gaussian:
|  test_mean  |       mean_0 |        rmsexp_0 | status_0   |
|:-------------------------------|-------------:|----------------:|:-----------|
| (1000, 'Minuit')               |  -0.014043   |     0.0193756   | True       |
| (1000, 'Pytorch_LBFGS')        |  -0.0150028  |     0.0165142   | True       |
| (1000, 'Pytorch_LBFGS_CUDA')   |  -0.0150025  |     0.0165141   | True       |
| (1000, 'Scipy_LM')             |  -0.0130124  |     0.0173673   | True       |
| (10000, 'Minuit')              |  -0.00771962 |     0.00310101  | True       |
| (10000, 'Pytorch_LBFGS')       |  -0.151017   | 78613           | True       |
| (10000, 'Pytorch_LBFGS_CUDA')  |  -0.150973   | 76862.4         | True       |
| (10000, 'Scipy_LM')            |  -1.33195    |    43.244       | True       |
| (100000, 'Minuit')             | nan          |   nan           | False      |
| (100000, 'Pytorch_LBFGS')      |  -0.435192   |     0.000745285 | False      |
| (100000, 'Pytorch_LBFGS_CUDA') |  -0.437151   |     0.000745085 | False      |
| (100000, 'Scipy_LM')           |  -0.0508745  |   inf           | True       |

|   test_RMS       |       std_0 |   bootstrap_std_0 |   rms_estimate_0 | status_0   |
|:-------------------------------|------------:|------------------:|-----------------:|:-----------|
| (1000, 'Minuit')               |   0.0491534 |          0.203825 |        0.106125  | True       |
| (1000, 'Pytorch_LBFGS')        |   0.0516665 |          0.292519 |        0.0904519 | True       |
| (1000, 'Pytorch_LBFGS_CUDA')   |   0.0516656 |          0.291537 |        0.0904515 | True       |
| (1000, 'Scipy_LM')             |   0.0487357 |          2.5264   |        0.0951246 | True       |
| (10000, 'Minuit')              |   0.0129782 |         37.7761   |        0.0169849 | True       |
| (10000, 'Pytorch_LBFGS')       |   0.723285  |          0.252473 |   430581         | False      |
| (10000, 'Pytorch_LBFGS_CUDA')  |   0.723042  |          0.271324 |   420993         | False      |
| (10000, 'Scipy_LM')            |   7.1585    |        299.624    |      236.857     | False      |
| (100000, 'Minuit')             | nan         |          0.170431 |      nan         | False      |
| (100000, 'Pytorch_LBFGS')      |   2.34731   |          9.41946  |        0.0040821 | False      |
| (100000, 'Pytorch_LBFGS_CUDA') |   2.35878   |          9.36116  |        0.004081  | False      |
| (100000, 'Scipy_LM')           |   0.281094  |          2.14387  |      inf         | False      |

|         test_pull          |   pull_mean_0 |   pull_std_0 | status_0   |
|:-------------------------------|--------------:|-------------:|:-----------|
| (1000, 'Minuit')               |     -0.403263 |     1.07598  | True       |
| (1000, 'Pytorch_LBFGS')        |     -0.282309 |     0.852829 | True       |
| (1000, 'Pytorch_LBFGS_CUDA')   |     -0.282309 |     0.852829 | True       |
| (1000, 'Scipy_LM')             |     -0.255318 |     0.851948 | True       |
| (10000, 'Minuit')              |     -0.370398 |     1.22762  | True       |
| (10000, 'Pytorch_LBFGS')       |     -0.129053 |     0.812783 | True       |
| (10000, 'Pytorch_LBFGS_CUDA')  |     -0.128972 |     0.812941 | True       |
| (10000, 'Scipy_LM')            |     -0.165702 |     0.789382 | True       |
| (100000, 'Minuit')             |    nan        |   nan        | False      |
| (100000, 'Pytorch_LBFGS')      |   -inf        |   nan        | False      |
| (100000, 'Pytorch_LBFGS_CUDA') |   -inf        |   nan        | False      |
| (100000, 'Scipy_LM')           |      0.145834 |     0.917947 | True       |

|                                |   chisq_mean |    chisq_std | status   |
|:-------------------------------|-------------:|-------------:|:---------|
| (1000, 'Minuit')               |     0.999494 |   0.0472108  | True     |
| (1000, 'Pytorch_LBFGS')        |     0.998333 |   0.0445175  | True     |
| (1000, 'Pytorch_LBFGS_CUDA')   |     0.998333 |   0.0445175  | True     |
| (1000, 'Scipy_LM')             |     0.999118 |   0.0439541  | True     |
| (10000, 'Minuit')              |     0.996023 |   0.00932508 | True     |
| (10000, 'Pytorch_LBFGS')       |     2.33366  |   7.30871    | False    |
| (10000, 'Pytorch_LBFGS_CUDA')  |     2.33366  |   7.30871    | False    |
| (10000, 'Scipy_LM')            |     0.999819 |   0.011573   | True     |
| (100000, 'Minuit')             |   nan        | nan          | False    |
| (100000, 'Pytorch_LBFGS')      |     2.41003  |   7.59761    | False    |
| (100000, 'Pytorch_LBFGS_CUDA') |     2.41003  |   7.59761    | False    |
| (100000, 'Scipy_LM')           |     1.98373  |   5.39279    | False    |

|         timing       |      time |   n_iter |
|:-------------------------------|----------:|---------:|
| ('Minuit', 1000)               | 0.0173873 | 235.549  |
| ('Minuit', 10000)              | 0.0400028 | 235.351  |
| ('Minuit', 100000)             | 0.436128  | 250.68   |
| ('Pytorch_LBFGS', 1000)        | 0.0268344 |  14.2533 |
| ('Pytorch_LBFGS', 10000)       | 0.0344587 |  14.4044 |
| ('Pytorch_LBFGS', 100000)      | 0.141242  |  14.6511 |
| ('Pytorch_LBFGS_CUDA', 1000)   | 0.357024  |  14.2622 |
| ('Pytorch_LBFGS_CUDA', 10000)  | 0.350904  |  14.3689 |
| ('Pytorch_LBFGS_CUDA', 100000) | 0.406599  |  14.6233 |
| ('Scipy_LM', 1000)             | 0.0044925 |  25.8489 |
| ('Scipy_LM', 10000)            | 0.024735  |  30.5964 |
| ('Scipy_LM', 100000)           | 0.296258  |  24.4334 |

**Comment by miranov25** [comment]
Looks like many non linear fits failed and test failed because of outliers. Outlier filtering has to be implmented 

### To do - outliers removal and status counters

- Print failure/success counters
- remove failures from the samples - using formal criteria of failure
  * some boolen value:
  * max iteration reached ...
  * infinities in parameter vectors
  * to use scipy criteria for fit failures
  * bitmask:
    * parameters  NonOK
    * covariance matrix NotOK
    * chi2Cut - if defined    ??? 
    * chi2/<chi2>_median - if defined   ??? 
- using user defined cost function cut as an option for bootstrap and for the ransac:
  * bootstrap criteria to remove fit:
  * user defined:
  * chi2CutAbs  - if defined    ??? 
  * chi2CutRelMed  - chi2/<chi2>_median - if defined   ???

**Comment by miranov25** [comment]
Merging changes - but next steps defined above

**Pull request merged**
