### PR TITLE
PWGPP-576 chisq cut

### PR DESCRIPTION
**Pull request by pl0xz0rz**
This PR:
-Fixes the first parameter of gaussian fitfunc being 1/sigma^2 instead of sigma^2
-Adds fit_status to pytorch fitter curve_fit, so far it only stores the number of iterations and whether the parameters are valid (no NaN, nu ber of iterations not exceeded)
-Adds chisq cut (removes outlier fits with chisq >> median chisq)

### CODE REVIEW

**Comment by pl0xz0rz** [comment]
Exponential (nfits = 15)

|                           |       mean_0 |   bootstrap_mean_0 |    rmsexp_0 | status_0   |
|:--------------------------|-------------:|-------------------:|------------:|:-----------|
| (1000, 'Minuit')          | -0.00131015  |       -0.00166037  | 0.00610709  | True       |
| (1000, 'Pytorch_LBFGS')   | -0.00127319  |       -0.000875443 | 0.00641909  | True       |
| (1000, 'Scipy_LM')        | -0.00127088  |       -0.000280843 | 0.00629181  | True       |
| (10000, 'Minuit')         | -0.00235901  |       -0.00275699  | 0.00104025  | True       |
| (10000, 'Pytorch_LBFGS')  | -0.000714198 |       -0.00116607  | 0.00128045  | True       |
| (10000, 'Scipy_LM')       | -0.000934268 |       -0.00113579  | 0.00127702  | True       |
| (100000, 'Minuit')        | -0.00215301  |       -0.000325911 | 0.00023395  | False      |
| (100000, 'Pytorch_LBFGS') | -0.00049445  |       -0.000462759 | 0.000707901 | True       |
| (100000, 'Scipy_LM')      | -0.000494475 |       -0.000463983 | 0.000706416 | True       |

|                           |        std_0 |   bootstrap_std_0 |   rms_estimate_0 | status_0   |
|:--------------------------|-------------:|------------------:|-----------------:|:-----------|
| (1000, 'Minuit')          |   0.0154208  |        0.0206108  |      0.0236527   | True       |
| (1000, 'Pytorch_LBFGS')   |   0.0154223  |        0.0131565  |      0.024861    | True       |
| (1000, 'Scipy_LM')        |   0.0154244  |        0.0170687  |      0.0243681   | True       |
| (10000, 'Minuit')         |   0.00762901 |        0.00468114 |      0.00402888  | False      |
| (10000, 'Pytorch_LBFGS')  |   0.00441197 |        0.00374931 |      0.00495916  | True       |
| (10000, 'Scipy_LM')       |   0.00521444 |        0.00376123 |      0.00494586  | True       |
| (100000, 'Minuit')        | nan          |        0.0021352  |      0.000906083 | False      |
| (100000, 'Pytorch_LBFGS') |   0.00347092 |        0.00175955 |      0.00274169  | True       |
| (100000, 'Scipy_LM')      |   0.00347101 |        0.00176047 |      0.00273594  | True       |

|                           |   pull_mean_0 |   pull_std_0 | status_0   |
|:--------------------------|--------------:|-------------:|:-----------|
| (1000, 'Minuit')          |    -0.180776  |     1.11823  | True       |
| (1000, 'Pytorch_LBFGS')   |    -0.129238  |     1.0028   | True       |
| (1000, 'Scipy_LM')        |    -0.12903   |     1.00395  | True       |
| (10000, 'Minuit')         |    -0.13414   |     1.31979  | True       |
| (10000, 'Pytorch_LBFGS')  |     0.0657977 |     0.786949 | True       |
| (10000, 'Scipy_LM')       |     0.0513972 |     0.809819 | True       |
| (100000, 'Minuit')        |    -2.37617   |   nan        | False      |
| (100000, 'Pytorch_LBFGS') |    -0.125872  |     1.33348  | True       |
| (100000, 'Scipy_LM')      |    -0.125974  |     1.33359  | True       |

|                           |   chisq_mean |    chisq_std | status   |
|:--------------------------|-------------:|-------------:|:---------|
| (1000, 'Minuit')          |     0.998351 |   0.0311227  | True     |
| (1000, 'Pytorch_LBFGS')   |     0.998351 |   0.0311227  | True     |
| (1000, 'Scipy_LM')        |     0.998351 |   0.0311227  | True     |
| (10000, 'Minuit')         |     0.998333 |   0.0108866  | True     |
| (10000, 'Pytorch_LBFGS')  |     0.999223 |   0.0101604  | True     |
| (10000, 'Scipy_LM')       |     0.999223 |   0.0101604  | True     |
| (100000, 'Minuit')        |     1.00742  | nan          | True     |
| (100000, 'Pytorch_LBFGS') |     1.00003  |   0.00395566 | True     |
| (100000, 'Scipy_LM')      |     1.00003  |   0.00395561 | True     |

|                           |       time |   n_iter |
|:--------------------------|-----------:|---------:|
| ('Minuit', 1000)          | 0.00836851 | 71.8267  |
| ('Minuit', 10000)         | 0.0209664  | 70.2     |
| ('Minuit', 100000)        | 0.211289   | 66.8267  |
| ('Pytorch_LBFGS', 1000)   | 0.0244823  | 10.12    |
| ('Pytorch_LBFGS', 10000)  | 0.0335742  |  9.87556 |
| ('Pytorch_LBFGS', 100000) | 0.256962   | 10.8178  |
| ('Scipy_LM', 1000)        | 0.00309554 | 15.0089  |
| ('Scipy_LM', 10000)       | 0.0182635  | 14.3422  |
| ('Scipy_LM', 100000)      | 0.177082   | 14.6889  |

**Comment by pl0xz0rz** [comment]
Gaussian (nfits = 15)
|                           |       mean_0 |   bootstrap_mean_0 |    rmsexp_0 | status_0   |
|:--------------------------|-------------:|-------------------:|------------:|:-----------|
| (1000, 'Minuit')          | -0.0027726   |       -0.000206226 | 0.00269143  | True       |
| (1000, 'Pytorch_LBFGS')   | -0.000111167 |       -0.0022617   | 0.00538502  | True       |
| (1000, 'Scipy_LM')        | -0.00264803  |       -0.00267505  | 0.0163363   | True       |
| (10000, 'Minuit')         | -0.00542589  |       -0.00766671  | 0.00106618  | False      |
| (10000, 'Pytorch_LBFGS')  | -0.00630804  |       -0.00120054  | 0.00436956  | True       |
| (10000, 'Scipy_LM')       | -0.00630585  |        0.00301884  | 0.00444984  | True       |
| (100000, 'Minuit')        |  0.255654    |        0.0185338   | 0.000116486 | False      |
| (100000, 'Pytorch_LBFGS') | -0.00179952  |       -0.00115203  | 0.00114822  | True       |
| (100000, 'Scipy_LM')      | -0.00180001  |        0.0067507   | 0.00114783  | True       |

|                           |      std_0 |   bootstrap_std_0 |   rms_estimate_0 | status_0   |
|:--------------------------|-----------:|------------------:|-----------------:|:-----------|
| (1000, 'Minuit')          | 0.0101612  |        0.0322786  |      0.0104239   | True       |
| (1000, 'Pytorch_LBFGS')   | 0.0118057  |        0.0204597  |      0.0208561   | True       |
| (1000, 'Scipy_LM')        | 0.0150334  |        0.0474466  |      0.0632704   | True       |
| (10000, 'Minuit')         | 0.00329069 |        0.00712867 |      0.00412931  | True       |
| (10000, 'Pytorch_LBFGS')  | 0.019236   |        0.00448001 |      0.0169232   | True       |
| (10000, 'Scipy_LM')       | 0.0192277  |        0.032094   |      0.0172341   | True       |
| (100000, 'Minuit')        | 0.360013   |        0.0765076  |      0.000451148 | False      |
| (100000, 'Pytorch_LBFGS') | 0.00599704 |        0.00154849 |      0.00444702  | True       |
| (100000, 'Scipy_LM')      | 0.00599624 |        0.0301613  |      0.00444551  | True       |

|                           |   pull_mean_0 |   pull_std_0 | status_0   |
|:--------------------------|--------------:|-------------:|:-----------|
| (1000, 'Minuit')          |  -0.376929    |  0.986954    | True       |
| (1000, 'Pytorch_LBFGS')   |  -0.109968    |  0.842478    | True       |
| (1000, 'Scipy_LM')        |  -0.112223    |  0.812784    | True       |
| (10000, 'Minuit')         |  -1.71843     |  1.46837     | False      |
| (10000, 'Pytorch_LBFGS')  |  -0.625594    |  1.24655     | True       |
| (10000, 'Scipy_LM')       |  -0.624579    |  1.24546     | True       |
| (100000, 'Minuit')        |   1.38396e+08 |  1.95721e+08 | False      |
| (100000, 'Pytorch_LBFGS') |   0.0412342   |  1.10487     | True       |
| (100000, 'Scipy_LM')      |   0.0409761   |  1.10516     | True       |

|                           |   chisq_mean |   chisq_std | status   |
|:--------------------------|-------------:|------------:|:---------|
| (1000, 'Minuit')          |     1.00192  |  0.0310609  | True     |
| (1000, 'Pytorch_LBFGS')   |     1.00646  |  0.0338787  | True     |
| (1000, 'Scipy_LM')        |     1.00422  |  0.0337738  | True     |
| (10000, 'Minuit')         |     0.991139 |  0.0168774  | True     |
| (10000, 'Pytorch_LBFGS')  |     1.00228  |  0.0134481  | True     |
| (10000, 'Scipy_LM')       |     1.00228  |  0.0134481  | True     |
| (100000, 'Minuit')        |     1.0832   |  0.104525   | True     |
| (100000, 'Pytorch_LBFGS') |     1.00129  |  0.0055654  | True     |
| (100000, 'Scipy_LM')      |     1.00129  |  0.00556542 | True     |

|                           |      time |   n_iter |
|:--------------------------|----------:|---------:|
| ('Minuit', 1000)          | 0.0334932 | 132      |
| ('Minuit', 10000)         | 0.113502  | 139.427  |
| ('Minuit', 100000)        | 0.916588  | 136.031  |
| ('Pytorch_LBFGS', 1000)   | 0.0418001 |  10.8978 |
| ('Pytorch_LBFGS', 10000)  | 0.0463894 |  10.8356 |
| ('Pytorch_LBFGS', 100000) | 0.317125  |  11.6    |
| ('Scipy_LM', 1000)        | 0.0093253 |  23.7828 |
| ('Scipy_LM', 10000)       | 0.0350022 |  21.567  |
| ('Scipy_LM', 100000)      | 0.330669  |  21.0717 |

**Comment by miranov25** [comment]
## To see impact of the cost Function cut (now called chi2 cut ) new test to be added:

## Bootstrap test
For gaussian -  non linear fits some fit can fail.

## Cost function cut can be used to remove outliers fit

To monitor -> to panda:

- mean after cut
- mean before cut
- median before cut
- median after cut
- rms before cut
- rms after cut
- rm estimator before cut
- rms estimator after cut
- fraction of accepted

Tests:

- mean test  -as for single fit
- before and after cleaning
- rms test as for single fit
- before and after cleaning

**Comment by miranov25** [comment]
Test looks comparable to previous one. 
Merging
But test for bootstrap to be added

**Pull request merged**
